apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  LEVEL_NAME: "littlewolfacres"
  GAMEMODE: "survival"
  DIFFICULTY: "normal"
  MAX_PLAYERS: "2"
  SERVER_NAME: "Little Wolf Acres"
  ALLOW_CHEATS: "false"
  ONLINE_MODE: "true"
