apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      containers:
        - name: minecraft-bedrock
          image: itzg/minecraft-bedrock-server:latest
          envFrom:
            - configMapRef:
                name: minecraft-config
          ports:
            - containerPort: 19132
              protocol: UDP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"

      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
