apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/speddling/homelab
    targetRevision: master
    path: services/synapse/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: synapse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
