apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-db
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
