apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: navidrome
spec:
  type: NodePort
  selector:
    app: navidrome
  ports:
    - port: 4533
      targetPort: 4533
      nodePort: 30533  # Access via http://monolith.local:30533
