---
- name: Configure exporters
  hosts: watchtower
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../../../../ansible/vars/main.yml"
    - "{{ playbook_dir }}/../../../../ansible/vars/vault.yml"

  roles:
    - exporters
